# Generated by Django 2.0.2 on 2018-09-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('entry_date', models.DateTimeField(verbose_name='entry date')),
                ('instrument', models.CharField(max_length=10)),
                ('setup', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('stop_loss', models.IntegerField(default=0)),
                ('take_profit', models.IntegerField(default=0)),
                ('expiration_date', models.DateTimeField(verbose_name='expiration date')),
                ('strike', models.IntegerField(default=0)),
                ('premium', models.IntegerField(default=0)),
                ('theta', models.IntegerField(default=0)),
                ('delta', models.IntegerField(default=0)),
                ('vega', models.IntegerField(default=0)),
                ('exit_date', models.DateTimeField(verbose_name='exit date')),
                ('exit_price', models.IntegerField(default=0)),
                ('pl', models.IntegerField(default=0)),
                ('breakeven', models.CharField(max_length=3)),
                ('fees', models.IntegerField(default=0)),
                ('highest_price', models.IntegerField(default=0)),
                ('lowest_price', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=200)),
                ('screenshots', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Author')),
            ],
        ),
    ]
